### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by BennyStrobes** [xiangzhou/GEMMA#30]
Hi, I'm trying to install gemma onto a linux cluster. However my version of gsl is not in the standard '/usr/bin' location and cannot be installed there because of admin privileges. 

Regardless, I cannot get the GEMMA Makefile to find where gsl is installed on the cluster. If anyone could give advice on how to edit the Makefile to correctly find gsl, that would be greatly appreciated.

Thanks!

**Comment by timflutre** [comment]
Did you try something like this? `make LDFLAGS=-L/usr/local/lib` (replace `/usr/local/lib` by the path to where you installed the GSL)

**Comment by pcarbo** [comment]
@BennyStrobes Are you still having problems with this issue?

**Comment by pjotrp** [comment]
I think we should close this.
