### ISSUE TITLE
GEMMA does not compile

### ISSUE THREAD

**Issue by samfux84** [xiangzhou/GEMMA#32]
./src/io.o: In function `GetabIndex(unsigned long, unsigned long, unsigned long)':
io.cpp:(.text+0x4ae0): multiple definition of `GetabIndex(unsigned long, unsigned long, unsigned long)'
./src/param.o:param.cpp:(.text+0x2500): first defined here
./src/lmm.o: In function `GetabIndex(unsigned long, unsigned long, unsigned long)':
lmm.cpp:(.text+0x1760): multiple definition of `GetabIndex(unsigned long, unsigned long, unsigned long)'
./src/param.o:param.cpp:(.text+0x2500): first defined here
./src/vc.o: In function `GetabIndex(unsigned long, unsigned long, unsigned long)':
vc.cpp:(.text+0x1600): multiple definition of `GetabIndex(unsigned long, unsigned long, unsigned long)'
./src/param.o:param.cpp:(.text+0x2500): first defined here
./src/vc.o: In function `ReadHeader(std::string const&, HEADER&)':
vc.cpp:(.text+0x81d0): multiple definition of `ReadHeader(std::string const&, HEADER&)'
./src/io.o:io.cpp:(.text+0x6cd0): first defined here
collect2: error: ld returned 1 exit status
make: *** [bin/gemma] Error 1

**Comment by samfux84** [comment]
Code was downloaded with

git clone https://github.com/xiangzhou/GEMMA.git

Using GCC 4.8.2, GSL 1.16, OpenBLAS 0.2.13

**Comment by pcarbo** [comment]
Hi @samfux84,

Can you please try compiling again with this latest version of GEMMA (`master` branch)? I think I have fixed this issue, but I wanted to double-check with you.

Peter

**Comment by samfux84** [comment]
Thank you for fixing the problem. GEMMA (master branch) now compiles.
