### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by tseemann** [xiangzhou/GEMMA#33]
Needed for packaging in Brew and Conda.

**Comment by pcarbo** [comment]
Hi @tseemann,

I've created [a release of GEMMA 0.95a](https://github.com/xiangzhou/GEMMA/releases/tag/v0.95a).

Please let us know if you need binaries of the Mac OS X and/or Linux versions for Brew and Conda.

Thanks for your help in making GEMMA available in Brew and Conda, and let me know if there is anything else I can do to make this happen.

Peter

**Comment by pjotrp** [comment]
Good stuff @pcarbo. Latest compiles fine in GNU Guix. When you do a release I'll push it into mainline.

**Comment by pcarbo** [comment]
@pjotrp @tseemann I have made a new release ([0.95.2a](https://github.com/xiangzhou/GEMMA/releases/tag/v0.95.2a)), which includes binaries built on Linux and Mac. Will this work for you?

**Comment by pjotrp** [comment]
I packaged it for GNU Guix (https://gitlab.com/genenetwork/guix-bioinformatics/commit/a0f4e5a7279625ecd8391f5412e54158bee51dd1). 

Can you make a new release because 0.95a does not compile, but the latest git does. Also make it a stable 0.95 or 0.95.1 release. This code has been tested for a while in GeneNetwork and Guix does not like to include alpha packages.

**Comment by pcarbo** [comment]
> Can you make a new release because 0.95a does not compile, but the latest git does.

Have you tried the [latest release, v0.95.2a](https://github.com/xiangzhou/GEMMA/releases/tag/v0.95.2a)?

> Also make it a stable 0.95 or 0.95.1 release.

Sure, I can create a new release, e.g., `v0.96`. Do I simply remove the "a" from the version, and remove the "pre-release" label? Or is there something else I need to do? e.g., make a `1.0` version?

**Comment by pjotrp** [comment]
Any number is fine as long as it does not say alpha, pre or rc ;). Numbering is mostly preference based. I would opt for 0.95 or 0.96. I would only tag x.xx releases. People who want/need to test stuff should pull from git instead.

**Comment by pcarbo** [comment]
@pjotrp I created a new (non-alpha) release: [v0.96](https://github.com/xiangzhou/GEMMA/releases/tag/v0.96).

**Comment by pjotrp** [comment]
It works and will go into Guix. @tseemann it should also work on bioconda, but you ought to take a look at Guix. I am presenting at BOSC. Guix and conda go well together.

**Comment by pjotrp** [comment]
gemma is now part of GNU Guix! http://git.savannah.gnu.org/cgit/guix.git/commit/?id=2b18ad054cf5a09582bc96ac7755452e7a5924e1

**Comment by pjotrp** [comment]
@tseemann there is still no package in bioconda. Who can do this?

**Comment by pcarbo** [comment]
@pjotrp I'm sorry, I don't have any experience with this.

**Comment by tseemann** [comment]
Conda is hard ...  maybe @slugger70 can try, and use my Brew recipe as a basis:
```
class Gemma < Formula
  desc "Genome-wide Efficient Mixed Model Association"
  homepage "http://www.xzlab.org/software.html"
  # doi "10.1038/ng.2310"
  # tag "bioinformatics"

  url "https://github.com/xiangzhou/GEMMA/archive/v0.96.tar.gz"
  sha256 "4208e75c9ee1d1e88517ceb62bd5e74b732a931279138b8ebb22b46782b5be14"

  head "https://github.com/xiangzhou/GEMMA"

  depends_on "zlib" unless OS.mac?
  depends_on "openblas"
  depends_on "gsl"

  def install
    system "make", "FORCE_DYNAMIC=1"
    bin.install Dir["bin/*"]
    doc.install Dir["doc/*"], "README.txt"
    pkgshare.install "example"
  end

  test do
    assert_match "eigen", shell_output("#{bin}/gemma -h 2>&1")
  end
end
```

**Comment by pjotrp** [comment]
That should help. The Guix definition is here: https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/bioinformatics.scm?id=v0.13.0-1229-g5143517#n2712 and looks rather similar. I'll experiment with openblas soon. I'll be at the hackathon in Prague in two weeks and I may get someone to help with bioconda.

**Comment by pjotrp** [comment]
Let's continue here https://github.com/xiangzhou/GEMMA/issues/52
