### ISSUE TITLE
Segmentation faults when running example in demo.txt 

### ISSUE THREAD

**Issue by nmc97** [xiangzhou/GEMMA#36]
I've been going through the demo and have experienced segmentation faults for one of the example processes. The rest worked fine.

On command line:

	> ../bin/gemma -g mouse_hs1940.geno.txt.gz -p mouse_hs1940.pheno.txt -n 1 6 -a mouse_hs1940.anno.txt -k ./output/mouse_hs1940.cXX.txt -lmm -o mouse_hs1940_CD8MCH_lmm

	Reading Files ... 
	## number of total individuals = 1940
	## number of analyzed individuals = 1197
	## number of covariates = 1
	## number of phenotypes = 2
	## number of total SNPs = 12226
	## number of analyzed SNPs = 10758
	Start Eigen-Decomposition...
	REMLE estimate for Vg in the null model: 
	1.3940  
	-0.2267 2.0817  
	se(Vg): 
	0.1567  
	0.1363  0.2359  
	REMLE estimate for Ve in the null model: 
	0.3489  
	0.0491  0.4144  
	se(Ve): 
	0.0206  
	0.0166  0.0267  
	REMLE likelihood = -2855.1664
	MLE estimate for Vg in the null model: 
	1.3959  
	-0.2267 2.0854  
	se(Vg): 
	0.1568  
	0.1365  0.2361  
	MLE estimate for Ve in the null model: 
	0.3483  
	0.0490  0.4136  
	se(Ve): 
	0.0206  
	0.0166  0.0266  
	MLE likelihood = -2856.0280
	Reading SNPs  ==================================================100.00%
	Segmentation fault (core dumped)

Running on gdb:

	(gdb) file ../bin/gemma
	Reading symbols from ../bin/gemma...done.
	(gdb) run -g mouse_hs1940.geno.txt.gz -p mouse_hs1940.pheno.txt -n 1 6 -a mouse_hs1940.anno.txt -k ./output/mouse_hs1940.cXX.txt -lmm -o mouse_hs1940_CD8MCH_lmm
	Starting program: /home/ubuntu/Nic/Programs/bugwas/GEMMA/bin/gemma -g mouse_hs1940.geno.txt.gz -p mouse_hs1940.pheno.txt -n 1 6 -a mouse_hs1940.anno.txt -k ./output/mouse_hs1940.cXX.txt -lmm -o mouse_hs1940_CD8MCH_lmm
	Reading Files ... 
	## number of total individuals = 1940
	## number of analyzed individuals = 1197
	## number of covariates = 1
	## number of phenotypes = 2
	## number of total SNPs = 12226
	## number of analyzed SNPs = 10758
	Start Eigen-Decomposition...
	REMLE estimate for Vg in the null model: 
	1.3940  
	-0.2267 2.0817  
	se(Vg): 
	0.1567  
	0.1363  0.2359  
	REMLE estimate for Ve in the null model: 
	0.3489  
	0.0491  0.4144  
	se(Ve): 
	0.0206  
	0.0166  0.0267  
	REMLE likelihood = -2855.1664
	MLE estimate for Vg in the null model: 
	1.3959  
	-0.2267 2.0854  
	se(Vg): 
	0.1568  
	0.1365  0.2361  
	MLE estimate for Ve in the null model: 
	0.3483  
	0.0490  0.4136  
	se(Ve): 
	0.0206  
	0.0166  0.0266  
	MLE likelihood = -2856.0280
	Reading SNPs  ==================================================100.00%

	Program received signal SIGSEGV, Segmentation fault.
	0x000000000046d369 in MVLMM::WriteFiles() ()
----

I got a similar error after using the down-loadable executable and compiling it myself.

If anyone can help me understand what this means and what I can do that would be great.
Thanks!

**Comment by pcarbo** [comment]
Hi @nmc97,

It appears that Xiang introduced a bug in GEMMA sometime between versions 0.94a and 0.95a; I was able to reproduce your bug with GEMMA 0.95a, and I did not get a segmentation fault with GEMMA 0.94a. So one temporary solution would be to download the v0.94 executable from [here](http://www.xzlab.org/software.html) or [here](https://github.com/xiangzhou/GEMMA/issues/21#issuecomment-281121103).

@xiangzhou, are you able to reproduce this segmentation fault? If so, could you investigate this bug?

Peter

**Comment by xiangzhou** [comment]
This bug inside mvlmm.cpp is fixed now.

**Comment by nmc97** [comment]
Thank you both!
