### ISSUE TITLE
FYI - updated Brew formula to 0.96

### ISSUE THREAD

**Issue by tseemann** [xiangzhou/GEMMA#44]
```
brew tap homebrew/science
brew tap tseemann/bioinformatics-linux
brew install gemma
# or brew install gemma --HEAD for current github master
```

Should work on MacOS too.

I will eventually get it into `homebrew-science` main.

**Comment by pcarbo** [comment]
That's great @tseeman. I was able to install it on my MacBook Pro with the following commands:

```bash
brew tap tseemann/bioinformatics-linux
brew install gemma
```

Note I got the following warning:

```
Warning: tseemann/bioinformatics-linux/gemma dependency gcc was 
built with a different C++ standard library (libstdc++ from clang). 
This may cause problems at runtime.
```

But it seems to be working despite this warning (didn't test it comprehensively, of course).

I've attached the full output from `brew install gemma` in case you are interested.

[brew_install_gemma.out.gz](https://github.com/xiangzhou/GEMMA/files/1046613/brew_install_gemma.out.gz)

**Comment by tseemann** [comment]
I only tested in on Linuxbrew (hence my repo name), and on Mac Brew I use `gcc` not `clang`, so i probably wouldn't encounter this problem.

**Comment by rafmarcondes** [comment]
I'm getting the same warning as @pcarbo, but it does give me an error at runtime. Any thoughts?

(base) a4-d1-8c-60-8d-82:usr Rafael$ brew install brewsci/bio/gemma
==> Installing gemma from brewsci/bio
==> Downloading https://linuxbrew.bintray.com/bottles-bio/gemma-0.98.1.sierra.bottle.tar.gz
Already downloaded: /Users/Rafael/Library/Caches/Homebrew/downloads/a3b5c6a385d594ca4fe622c5eb3e68e5b1a87da7e487bd052d9efc2f30f3d3fd--gemma-0.98.1.sierra.bottle.tar.gz
==> Pouring gemma-0.98.1.sierra.bottle.tar.gz
Warning: brewsci/bio/gemma dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/gemma/0.98.1: 46 files, 89.8MB
(base) a4-d1-8c-60-8d-82:usr Rafael$ cd /usr/local/Cellar/gemma/0.98.1
(base) a4-d1-8c-60-8d-82:0.98.1 Rafael$ gemma
dyld: Library not loaded: /usr/local/opt/gsl/lib/libgsl.23.dylib
  Referenced from: /usr/local/bin/gemma
  Reason: image not found
Abort trap: 6
