### ISSUE TITLE
Use Unix mode for source files

### ISSUE THREAD

**Issue by pjotrp** [xiangzhou/GEMMA#49]
@pcarbo can we default to Unix format files? I have fixed a few compile time bugs on Linux, but you are using some other format which messes the diffs up. It should be a simple setting in your editor. I'll add a pull request. Note, I am working from the master branch and I am assuming it should be working. If it is broken in some way we should use a different branch. Currently it is broken on Linux with a recent gcc.

**Comment by pjotrp** [comment]
Also set your editor to remove eol spaces.

The main file that does not use Unix format is logistic.cpp.

**Comment by pjotrp** [comment]
If you want I can convert all source files to the required format in one patch set - so it is clear no real functionality changed and we can continue from there.

**Comment by pcarbo** [comment]
@pjotrp Yes, please go ahead and do this (if this isn' already addressed by your pull requests). I'm quite certain that I did not introduce these eol spaces---I work on a Mac, and I have never had this issue before (it is typically a problem when collaborating with people that edit files in Windows). Thank you.

**Comment by pcarbo** [comment]
See Pull Request #51.

**Comment by pjotrp** [comment]
Thanks 👍(my) new patches should be clean from now on.
